import React from "react";
import Head from "next/head";

export default function Title() {
  return (
    <Head>
      <title>Create Next App cuy</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
